version: "3.8"
services:
  mysql:
    image: mysql:5.7.32
    container_name: myservice-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./src/main/resources/db:/docker-entrypoint-initdb.d
    command: mysqld --skip-ssl --character_set_server=utf8mb4 --lower_case_table_names=1

  redis:
    image: redis:7.0.5
    container_name: myservice-redis
    ports:
      - "6379:6379"
