server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myservice?serverTimeZone=UTC
    username: svc-user
    password: svc-password
  redis:
    host: localhost
    port: 6379

application:
  user:
    authentication:
      authentication-number-ttl-ms: 1800000  # 1000 * 60 * 30 = 30 minutes